# Generated by Django 4.1.7 on 2023-03-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField(max_length=27, null=True)),
                ('roll_number', models.CharField(max_length=10, null=True)),
                ('email_adress', models.EmailField(max_length=50, null=True)),
                ('nationality', models.CharField(max_length=150, null=True)),
                ('employee_id', models.PositiveSmallIntegerField(null=True)),
                ('id_number', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('medical_report', models.FileField(null=True, upload_to='documents/')),
                ('date_of_enrollment', models.DateField(max_length=10, null=True)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('languages', models.CharField(choices=[('E', 'English'), ('S', 'Swahili'), ('K', 'Kikuyu'), ('R', 'kinyarwanda'), ('U', 'Kiganda')], max_length=2, null=True)),
                ('laptop_serial_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
